def display_menu():
    print("=====Pharmacy Inventory=====")
    print()
    print("1. View inventory")
    print("2. Add medicine")
    print("3. Remove medicine")
    print("4. Search Medicine")
    print("5. Update Quantity")
    print("6. Exit")
    print()